# File Path to Data Sourced from https://www.consumerfinance.gov/data-research/consumer-complaints/#download-the-data
config_complaints_file = 'D:/complaint_data/complaints.csv'
config_complaints_file_encoding = 'cp850'
config_complaints_narrative_column = 'Consumer complaint narrative'
config_model_folder = 'D:/complaint_labeling_neural_net/models/'
config_product_model_save_name = f'{config_model_folder}lstm_product_classifier.hdf5'
config_vectorizer_folder = 'D:/complaint_labeling_neural_net/vectorizers/'
config_proc_data_dir = 'D:/complaint_labeling_neural_net/processed_data/'
config_train_x_save_name = f'{config_proc_data_dir}train_sequences.npy'
config_test_x_save_name = f'{config_proc_data_dir}test_sequences.npy'
config_train_y_save_name = f'{config_proc_data_dir}train_y.npy'
config_test_y_save_name = f'{config_proc_data_dir}test_y.npy'
config_train_x_save_name_issue = f'{config_proc_data_dir}train_sequences_issue.npy'
config_test_x_save_name_issue = f'{config_proc_data_dir}test_sequences_issue.npy'
config_train_y_save_name_issue = f'{config_proc_data_dir}train_y_issue.npy'
config_test_y_save_name_issue = f'{config_proc_data_dir}test_y_issue.npy'



# Data Configuration
config_product_dict = {'Debt collection': 'Debt collection',
 'Credit reporting, credit repair services, or other personal consumer reports': 'Credit reporting',
 'Money transfer, virtual currency, or money service': 'Money transfers or virtual currency',
 'Mortgage': 'Mortgage',
 'Student loan': 'Student loan',
 'Vehicle loan or lease': 'Vehicle loan or lease',
 'Credit card or prepaid card': 'Card',
 'Checking or savings account': 'Checking or savings account',
 'Credit card': 'Card',
 'Payday loan, title loan, or personal loan': 'Consumer Loan',
 'Consumer Loan': 'Consumer Loan',
 'Payday loan': 'Consumer Loan',
 'Credit reporting': 'Credit reporting',
 'Prepaid card': 'Card',
 'Other financial service': 'Other financial service',
 'Bank account or service': 'Other financial service',
 'Money transfers': 'Money transfers or virtual currency',
 'Virtual currency': 'Money transfers or virtual currency'}


# Mapping of 'Product | Issue | Sub-issue' to Complaint Category
config_issue_dict = {"Card | Advertising | Changes in terms from what was offered or advertised" : "Marketing Rewards and Promotions",
"Card | Advertising | Confusing or misleading advertising about the card" : "Marketing Rewards and Promotions",
"Card | Advertising and Marketing Rewards and Promotions, including promotional offers | Confusing or misleading advertising about the credit card" : "Marketing Rewards and Promotions",
"Card | Advertising and Marketing Rewards and Promotions, including promotional offers | Didn't receive advertised or promotional terms" : "Marketing Rewards and Promotions",
"Card | Closing your account | Can't close your account" : "Closures and Cancellations",
"Card | Closing your account | Company closed your account" : "Closures and Cancellations",
"Card | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Card | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Card | Credit monitoring or identity theft protection services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Card | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Card | Credit monitoring or identity theft protection services | Received unwanted Marketing Rewards and Promotions or advertising" : "Marketing Rewards and Promotions",
"Card | Fees or interest | Charged too much interest" : "Fees Interest and Credit Limits",
"Card | Fees or interest | Problem with fees" : "Fees Interest and Credit Limits",
"Card | Fees or interest | Unexpected increase in interest rate" : "Fees Interest and Credit Limits",
"Card | Getting a credit card | Application denied" : "Applications and Qualifications",
"Card | Getting a credit card | Card opened as result of identity theft or fraud" : "Fraud",
"Card | Getting a credit card | Delay in processing application" : "Applications and Qualifications",
"Card | Getting a credit card | Problem getting a working replacement card" : "Account Management",
"Card | Getting a credit card | Sent card you never applied for" : "Account Management",
"Card | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Card | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Credit Reporting",
"Card | Improper use of your report | Report provided to employer without your written authorization" : "Credit Reporting",
"Card | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Card | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Card | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Card | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Card | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Card | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Card | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Card | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Card | Other features, terms, or problems | Add-on products and services" : "Other product problems",
"Card | Other features, terms, or problems | Credit card company forcing arbitration" : "Other product problems",
"Card | Other features, terms, or problems | Other problem" : "Other product problems",
"Card | Other features, terms, or problems | Privacy issues" : "Other product problems",
"Card | Other features, terms, or problems | Problem with balance transfer" : "Payments Withdrawals and Transfers",
"Card | Other features, terms, or problems | Problem with cash advances" : "Payments Withdrawals and Transfers",
"Card | Other features, terms, or problems | Problem with convenience check" : "Other product problems",
"Card | Other features, terms, or problems | Problem with customer service" : "Servicing",
"Card | Other features, terms, or problems | Problem with rewards from credit card" : "Marketing Rewards and Promotions",
"Card | Problem getting a card or closing an account | Don't want a card provided by your employer or the government" : "Closures and Cancellations",
"Card | Problem getting a card or closing an account | Trouble closing card" : "Closures and Cancellations",
"Card | Problem getting a card or closing an account | Trouble getting a working replacement card" : "Account Management",
"Card | Problem getting a card or closing an account | Trouble getting, activating, or registering a card" : "Account Management",
"Card | Problem when making payments | Problem during payment process" : "Payments Withdrawals and Transfers",
"Card | Problem when making payments | You never received your bill or did not know a payment was due" : "Billing",
"Card | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Card | Problem with a credit reporting company's investigation into an existing problem | Investigation took more than 30 days" : "Servicing",
"Card | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Servicing",
"Card | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Servicing",
"Card | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Servicing",
"Card | Problem with a purchase or transfer | Card company isn't resolving a dispute about a purchase or transfer" : "Transaction Disputes",
"Card | Problem with a purchase or transfer | Charged for a purchase or transfer you did not make with the card" : "Transaction Disputes",
"Card | Problem with a purchase or transfer | Overcharged for a purchase or transfer you did make with the card" : "Transaction Disputes",
"Card | Problem with a purchase shown on your statement | Card was charged for something you did not purchase with the card" : "Transaction Disputes",
"Card | Problem with a purchase shown on your statement | Credit card company isn't resolving a dispute about a purchase on your statement" : "Transaction Disputes",
"Card | Problem with a purchase shown on your statement | Overcharged for something you did purchase with the card" : "Transaction Disputes",
"Card | Problem with an overdraft | Was signed up for overdraft on card, but don't want to be" : "Other product problems",
"Card | Problem with overdraft | Overdraft charges" : "Other product problems",
"Card | Struggling to pay your bill | Credit card company won't work with you while you're going through financial hardship" : "Financial hardship",
"Card | Struggling to pay your bill | Filed for bankruptcy" : "Financial hardship",
"Card | Struggling to pay your bill | Problem lowering your monthly payments" : "Financial hardship",
"Card | Trouble using the card | Problem adding money" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Problem using the card to withdraw money from an ATM" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Problem with a check written from your prepaid card account" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Problem with direct deposit" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Trouble getting information about the card" : "Other product problems",
"Card | Trouble using the card | Trouble using the card to pay a bill" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Trouble using the card to send money to another person" : "Payments Withdrawals and Transfers",
"Card | Trouble using the card | Trouble using the card to spend money in a store or online" : "Purchase Issues",
"Card | Trouble using your card | Account sold or transferred to another company" : "Other product problems",
"Card | Trouble using your card | Can't use card to make purchases" : "Purchase Issues",
"Card | Trouble using your card | Credit card company won't increase or decrease your credit limit" : "Fees Interest and Credit Limits",
"Card | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Credit Reporting",
"Card | Unable to get your credit report or credit score | Problem getting your free annual credit report" : "Credit Reporting",
"Checking or savings account | Closing an account | Can't close your account" : "Closures and Cancellations",
"Checking or savings account | Closing an account | Company closed your account" : "Closures and Cancellations",
"Checking or savings account | Closing an account | Fees charged for closing account" : "Closures and Cancellations",
"Checking or savings account | Closing an account | Funds not received from closed account" : "Closures and Cancellations",
"Checking or savings account | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Checking or savings account | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Checking or savings account | Credit monitoring or identity theft protection services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Checking or savings account | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Checking or savings account | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Checking or savings account | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Marketing Rewards and Promotions",
"Checking or savings account | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Checking or savings account | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Checking or savings account | Managing an account | Banking errors" : "Account Management",
"Checking or savings account | Managing an account | Cashing a check" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Deposits and withdrawals" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Deposits or withdrawals" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Fee problem" : "Fees Interest and Credit Limits",
"Checking or savings account | Managing an account | Funds not handled or disbursed as instructed" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Problem accessing account" : "Account Management",
"Checking or savings account | Managing an account | Problem making or receiving payments" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Problem using a debit or ATM card" : "Payments Withdrawals and Transfers",
"Checking or savings account | Managing an account | Problem with fees or penalties" : "Fees Interest and Credit Limits",
"Checking or savings account | Managing an account | Problem with renewal" : "Account Management",
"Checking or savings account | Opening an account | Account opened as a result of fraud" : "Fraud",
"Checking or savings account | Opening an account | Confusing or missing disclosures" : "Marketing Rewards and Promotions",
"Checking or savings account | Opening an account | Didn't receive terms that were advertised" : "Marketing Rewards and Promotions",
"Checking or savings account | Opening an account | Unable to open an account" : "Applications and Qualifications",
"Checking or savings account | Problem caused by your funds being low | Bounced checks or returned payments" : "Payments Withdrawals and Transfers",
"Checking or savings account | Problem caused by your funds being low | Late or other fees" : "Fees Interest and Credit Limits",
"Checking or savings account | Problem caused by your funds being low | Non-sufficient funds and associated fees" : "Fees Interest and Credit Limits",
"Checking or savings account | Problem caused by your funds being low | Overdrafts and overdraft fees" : "Fees Interest and Credit Limits",
"Checking or savings account | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Checking or savings account | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Credit Reporting",
"Checking or savings account | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Credit Reporting",
"Checking or savings account | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Credit Reporting",
"Checking or savings account | Problem with a lender or other company charging your account | Can't stop withdrawals from your account" : "Transaction Disputes",
"Checking or savings account | Problem with a lender or other company charging your account | Money was taken from your account on the wrong day or for the wrong amount" : "Transaction Disputes",
"Checking or savings account | Problem with a lender or other company charging your account | Transaction was not authorized" : "Transaction Disputes",
"Checking or savings account | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Credit Reporting",
"Checking or savings account | Unable to get your credit report or credit score | Problem getting your free annual credit report" : "Credit Reporting",
"Consumer Loan | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Consumer Loan | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Consumer Loan | Credit monitoring or identity theft protection services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Consumer Loan | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Consumer Loan | Credit monitoring or identity theft protection services | Received unwanted Marketing Rewards and Promotions or advertising" : "Marketing Rewards and Promotions",
"Consumer Loan | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Consumer Loan | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Marketing Rewards and Promotions",
"Consumer Loan | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Consumer Loan | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Consumer Loan | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Consumer Loan | Problem with a credit reporting company's investigation into an existing problem | Investigation took more than 30 days" : "Servicing",
"Consumer Loan | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Credit Reporting",
"Consumer Loan | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Credit Reporting",
"Consumer Loan | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Credit Reporting",
"Consumer Loan | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Credit Reporting",
"Credit reporting | Credit monitoring or identity protection | Account terms and changes" : "Other product problems",
"Credit reporting | Credit monitoring or identity protection | Billing dispute" : "Billing",
"Credit reporting | Credit monitoring or identity protection | Problem cancelling or closing account" : "Closures and Cancellations",
"Credit reporting | Credit monitoring or identity protection | Problem with fraud alerts" : "Fraud",
"Credit reporting | Credit monitoring or identity protection | Receiving unwanted Marketing Rewards and Promotions/advertising" : "Marketing Rewards and Promotions",
"Credit reporting | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Credit reporting | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Credit reporting | Credit monitoring or identity theft protection services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Credit reporting | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Credit reporting | Credit monitoring or identity theft protection services | Received unwanted Marketing Rewards and Promotions or advertising" : "Marketing Rewards and Promotions",
"Credit reporting | Credit reporting company's investigation | Inadequate help over the phone" : "Servicing",
"Credit reporting | Credit reporting company's investigation | Investigation took too long" : "Servicing",
"Credit reporting | Credit reporting company's investigation | No notice of investigation status/result" : "Servicing",
"Credit reporting | Credit reporting company's investigation | Problem with statement of dispute" : "Servicing",
"Credit reporting | Dealing with your lender or servicer | Received bad information about your loan" : "Servicing",
"Credit reporting | Getting a credit card | Card opened as result of identity theft or fraud" : "Fraud",
"Credit reporting | Getting a loan or lease | Credit denial" : "Applications and Qualifications",
"Credit reporting | Identity theft protection or other monitoring services | Billing dispute for services" : "Billing",
"Credit reporting | Identity theft protection or other monitoring services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Credit reporting | Identity theft protection or other monitoring services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Credit reporting | Identity theft protection or other monitoring services | Problem with product or service terms changing" : "Other product problems",
"Credit reporting | Identity theft protection or other monitoring services | Received unwanted Marketing Rewards and Promotions or advertising" : "Marketing Rewards and Promotions",
"Credit reporting | Improper use of my credit report | Received Marketing Rewards and Promotions offer after opted out" : "Marketing Rewards and Promotions",
"Credit reporting | Improper use of my credit report | Report improperly shared by CRC" : "Credit Reporting",
"Credit reporting | Improper use of my credit report | Report shared with employer w/o consent" : "Credit Reporting",
"Credit reporting | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Credit reporting | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Credit Reporting",
"Credit reporting | Improper use of your report | Report provided to employer without your written authorization" : "Credit Reporting",
"Credit reporting | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Credit reporting | Incorrect information on credit report | Account status" : "Account Management",
"Credit reporting | Incorrect information on credit report | Account terms" : "Account Management",
"Credit reporting | Incorrect information on credit report | Information is not mine" : "Credit Reporting",
"Credit reporting | Incorrect information on credit report | Personal information" : "Credit Reporting",
"Credit reporting | Incorrect information on credit report | Public record" : "Credit Reporting",
"Credit reporting | Incorrect information on credit report | Reinserted previously deleted info" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Information is incorrect" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Information that should be on the report is missing" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Credit reporting | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Credit reporting | Problem when making payments | Problem during payment process" : "Payments Withdrawals and Transfers",
"Credit reporting | Problem with a company's investigation into an existing issue | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Credit reporting | Problem with a company's investigation into an existing issue | Investigation took more than 30 days" : "Servicing",
"Credit reporting | Problem with a company's investigation into an existing issue | Problem with personal statement of dispute" : "Credit Reporting",
"Credit reporting | Problem with a company's investigation into an existing issue | Their investigation did not fix an error on your report" : "Credit Reporting",
"Credit reporting | Problem with a company's investigation into an existing issue | Was not notified of investigation status or results" : "Credit Reporting",
"Credit reporting | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Credit reporting | Problem with a credit reporting company's investigation into an existing problem | Investigation took more than 30 days" : "Servicing",
"Credit reporting | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Credit Reporting",
"Credit reporting | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Credit Reporting",
"Credit reporting | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Credit Reporting",
"Credit reporting | Unable to get credit report/credit score | Problem getting my free annual report" : "Credit Reporting",
"Credit reporting | Unable to get credit report/credit score | Problem getting report or credit score" : "Credit Reporting",
"Credit reporting | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Credit Reporting",
"Credit reporting | Unable to get your credit report or credit score | Problem getting your free annual credit report" : "Credit Reporting",
"Debt collection | Attempts to collect debt not owed | Debt is not yours" : "Attempts to collect debt not owed",
"Debt collection | Attempts to collect debt not owed | Debt was already discharged in bankruptcy and is no longer owed" : "Attempts to collect debt not owed",
"Debt collection | Attempts to collect debt not owed | Debt was paid" : "Attempts to collect debt not owed",
"Debt collection | Attempts to collect debt not owed | Debt was result of identity theft" : "Attempts to collect debt not owed",
"Debt collection | Communication tactics | Called after sent written cease of comm" : "Servicing",
"Debt collection | Communication tactics | Called before 8am or after 9pm" : "Servicing",
"Debt collection | Communication tactics | Called outside of 8am-9pm" : "Servicing",
"Debt collection | Communication tactics | Frequent or repeated calls" : "Servicing",
"Debt collection | Communication tactics | Threatened to take legal action" : "Servicing",
"Debt collection | Communication tactics | Used obscene, profane, or other abusive language" : "Servicing",
"Debt collection | Communication tactics | Used obscene/profane/abusive language" : "Servicing",
"Debt collection | Communication tactics | You told them to stop contacting you, but they keep trying" : "Servicing",
"Debt collection | Cont'd attempts collect debt not owed | Debt is not mine" : "Attempts to collect debt not owed",
"Debt collection | Cont'd attempts collect debt not owed | Debt resulted from identity theft" : "Attempts to collect debt not owed",
"Debt collection | Cont'd attempts collect debt not owed | Debt was discharged in bankruptcy" : "Attempts to collect debt not owed",
"Debt collection | Cont'd attempts collect debt not owed | Debt was paid" : "Attempts to collect debt not owed",
"Debt collection | Disclosure verification of debt | Not disclosed as an attempt to collect" : "Servicing",
"Debt collection | Disclosure verification of debt | Not given enough info to verify debt" : "Servicing",
"Debt collection | Disclosure verification of debt | Right to dispute notice not received" : "Servicing",
"Debt collection | False statements or representation | Attempted to collect wrong amount" : "False statements or representation",
"Debt collection | False statements or representation | Impersonated an attorney or official" : "False statements or representation",
"Debt collection | False statements or representation | Impersonated attorney, law enforcement, or government official" : "False statements or representation",
"Debt collection | False statements or representation | Indicated committed crime not paying" : "False statements or representation",
"Debt collection | False statements or representation | Indicated shouldn't respond to lawsuit" : "False statements or representation",
"Debt collection | False statements or representation | Indicated you were committing crime by not paying debt" : "False statements or representation",
"Debt collection | False statements or representation | Told you not to respond to a lawsuit they filed against you" : "False statements or representation",
"Debt collection | Improper contact or sharing of info | Contacted employer after asked not to" : "Servicing",
"Debt collection | Improper contact or sharing of info | Contacted me after I asked not to" : "Servicing",
"Debt collection | Improper contact or sharing of info | Contacted me instead of my attorney" : "Servicing",
"Debt collection | Improper contact or sharing of info | Talked to a third party about my debt" : "Servicing",
"Debt collection | Taking/threatening an illegal action | Attempted to/Collected exempt funds" : "Threatening actions",
"Debt collection | Taking/threatening an illegal action | Seized/Attempted to seize property" : "Threatening actions",
"Debt collection | Taking/threatening an illegal action | Sued w/o proper notification of suit" : "Threatening actions",
"Debt collection | Taking/threatening an illegal action | Sued where didn't live/sign for debt" : "Threatening actions",
"Debt collection | Taking/threatening an illegal action | Threatened arrest/jail if do not pay" : "Threatening actions",
"Debt collection | Taking/threatening an illegal action | Threatened to sue on too old debt" : "Threatening actions",
"Debt collection | Threatened to contact someone or share information improperly | Contacted you after you asked them to stop" : "Servicing",
"Debt collection | Threatened to contact someone or share information improperly | Contacted you instead of your attorney" : "Servicing",
"Debt collection | Threatened to contact someone or share information improperly | Contacted your employer" : "Servicing",
"Debt collection | Threatened to contact someone or share information improperly | Talked to a third-party about your debt" : "Servicing",
"Debt collection | Took or threatened to take negative or legal action | Collected or attempted to collect exempt funds" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Seized or attempted to seize your property" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Sued you in a state where you do not live or did not sign for the debt" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Sued you without properly notifying you of lawsuit" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Threatened or suggested your credit would be damaged" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Threatened to arrest you or take you to jail if you do not pay" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Threatened to sue you for very old debt" : "Threatening actions",
"Debt collection | Took or threatened to take negative or legal action | Threatened to turn you in to immigration or deport you" : "Threatening actions",
"Debt collection | Written notification about debt | Didn't receive enough information to verify debt" : "Servicing",
"Debt collection | Written notification about debt | Didn't receive notice of right to dispute" : "Servicing",
"Debt collection | Written notification about debt | Notification didn't disclose it was an attempt to collect a debt" : "Servicing",
"Student loan | Can't repay my loan | Can't decrease my monthly payments" : "Financial hardship",
"Student loan | Can't repay my loan | Can't get flexible payment options" : "Financial hardship",
"Student loan | Can't repay my loan | Can't temporarily postpone payments" : "Financial hardship",
"Student loan | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Student loan | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Student loan | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Student loan | Credit monitoring or identity theft protection services | Received unwanted Marketing Rewards and Promotions or advertising" : "Marketing Rewards and Promotions",
"Student loan | Dealing with my lender or servicer | Don't agree with fees charged" : "Fees Interest and Credit Limits",
"Student loan | Dealing with my lender or servicer | Having problems with customer service" : "Servicing",
"Student loan | Dealing with my lender or servicer | Keep getting calls about my loan" : "Servicing",
"Student loan | Dealing with my lender or servicer | Need information about my balance/terms" : "Other product problems",
"Student loan | Dealing with my lender or servicer | Received bad information about my loan" : "Other product problems",
"Student loan | Dealing with my lender or servicer | Trouble with how payments are handled" : "Payments Withdrawals and Transfers",
"Student loan | Dealing with your lender or servicer | Don't agree with the fees charged" : "Fees Interest and Credit Limits",
"Student loan | Dealing with your lender or servicer | Keep getting calls about your loan" : "Servicing",
"Student loan | Dealing with your lender or servicer | Need information about your loan balance or loan terms" : "Other product problems",
"Student loan | Dealing with your lender or servicer | Problem with customer service" : "Servicing",
"Student loan | Dealing with your lender or servicer | Received bad information about your loan" : "Other product problems",
"Student loan | Dealing with your lender or servicer | Trouble with how payments are being handled" : "Payments Withdrawals and Transfers",
"Student loan | Getting a loan | Can't qualify for a loan" : "Applications and Qualifications",
"Student loan | Getting a loan | Confusing or misleading advertising" : "Marketing Rewards and Promotions",
"Student loan | Getting a loan | Denied loan" : "Applications and Qualifications",
"Student loan | Getting a loan | Fraudulent loan" : "Fraud",
"Student loan | Getting a loan | Problem with signing the paperwork" : "Account Management",
"Student loan | Getting a loan | Problem with the interest rate" : "Fees Interest and Credit Limits",
"Student loan | Getting a loan | Qualified for a better loan than the one offered" : "Applications and Qualifications",
"Student loan | Getting a loan | Qualify for a better loan than offered" : "Applications and Qualifications",
"Student loan | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Student loan | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Credit Reporting",
"Student loan | Improper use of your report | Report provided to employer without your written authorization" : "Credit Reporting",
"Student loan | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Student loan | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Student loan | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Student loan | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Student loan | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Student loan | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Student loan | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Student loan | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Student loan | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Student loan | Problem with a credit reporting company's investigation into an existing problem | Investigation took more than 30 days" : "Servicing",
"Student loan | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Servicing",
"Student loan | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Servicing",
"Student loan | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Servicing",
"Student loan | Struggling to repay your loan | Can't get other flexible options for repaying your loan" : "Financial hardship",
"Student loan | Struggling to repay your loan | Can't temporarily delay making payments" : "Financial hardship",
"Student loan | Struggling to repay your loan | Problem lowering your monthly payments" : "Financial hardship",
"Student loan | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Credit Reporting",
"Student loan | Unable to get your credit report or credit score | Problem getting your free annual credit report" : "Credit Reporting",
"Vehicle loan or lease | Credit monitoring or identity theft protection services | Billing dispute for services" : "Billing",
"Vehicle loan or lease | Credit monitoring or identity theft protection services | Didn't receive services that were advertised" : "Marketing Rewards and Promotions",
"Vehicle loan or lease | Credit monitoring or identity theft protection services | Problem canceling credit monitoring or identify theft protection service" : "Closures and Cancellations",
"Vehicle loan or lease | Credit monitoring or identity theft protection services | Problem with product or service terms changing" : "Other product problems",
"Vehicle loan or lease | Getting a loan or lease | Changes in terms mid-deal or after closing" : "Other product problems",
"Vehicle loan or lease | Getting a loan or lease | Confusing or misleading advertising" : "Marketing Rewards and Promotions",
"Vehicle loan or lease | Getting a loan or lease | Credit denial" : "Applications and Qualifications",
"Vehicle loan or lease | Getting a loan or lease | Fraudulent loan" : "Fraud",
"Vehicle loan or lease | Getting a loan or lease | High-pressure sales tactics" : "Servicing",
"Vehicle loan or lease | Getting a loan or lease | Problem with a trade-in" : "Applications and Qualifications",
"Vehicle loan or lease | Getting a loan or lease | Problem with additional add-on products or services purchased with the loan" : "Other product problems",
"Vehicle loan or lease | Getting a loan or lease | Problem with signing the paperwork" : "Other product problems",
"Vehicle loan or lease | Improper use of your report | Credit inquiries on your report that you don't recognize" : "Credit Reporting",
"Vehicle loan or lease | Improper use of your report | Received unsolicited financial product or insurance offers after opting out" : "Credit Reporting",
"Vehicle loan or lease | Improper use of your report | Report provided to employer without your written authorization" : "Credit Reporting",
"Vehicle loan or lease | Improper use of your report | Reporting company used your report improperly" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Account information incorrect" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Account status incorrect" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Information belongs to someone else" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Information is missing that should be on the report" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Old information reappears or never goes away" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Personal information incorrect" : "Credit Reporting",
"Vehicle loan or lease | Incorrect information on your report | Public record information inaccurate" : "Credit Reporting",
"Vehicle loan or lease | Managing the loan or lease | Billing problem" : "Billing",
"Vehicle loan or lease | Managing the loan or lease | Loan sold or transferred to another company" : "Other product problems",
"Vehicle loan or lease | Managing the loan or lease | Problem with additional products or services purchased with the loan" : "Other product problems",
"Vehicle loan or lease | Managing the loan or lease | Problem with fees charged" : "Fees Interest and Credit Limits",
"Vehicle loan or lease | Managing the loan or lease | Problem with the interest rate" : "Fees Interest and Credit Limits",
"Vehicle loan or lease | Problem with a credit reporting company's investigation into an existing problem | Difficulty submitting a dispute or getting information about a dispute over the phone" : "Servicing",
"Vehicle loan or lease | Problem with a credit reporting company's investigation into an existing problem | Investigation took more than 30 days" : "Servicing",
"Vehicle loan or lease | Problem with a credit reporting company's investigation into an existing problem | Problem with personal statement of dispute" : "Servicing",
"Vehicle loan or lease | Problem with a credit reporting company's investigation into an existing problem | Their investigation did not fix an error on your report" : "Servicing",
"Vehicle loan or lease | Problem with a credit reporting company's investigation into an existing problem | Was not notified of investigation status or results" : "Servicing",
"Vehicle loan or lease | Problems at the end of the loan or lease | Excess mileage, damage, or wear fees, or other problem after the lease is finish" : "Servicing",
"Vehicle loan or lease | Problems at the end of the loan or lease | Problem extending the lease" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Problem related to refinancing" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Problem when attempting to purchase vehicle at the end of the lease" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Problem while selling or giving up the vehicle" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Problem with paying off the loan" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Termination fees or other problem when ending the lease early" : "Other product problems",
"Vehicle loan or lease | Problems at the end of the loan or lease | Unable to receive car title or other problem after the loan is paid off" : "Other product problems",
"Vehicle loan or lease | Struggling to pay your loan | Denied request to lower payments" : "Financial hardship",
"Vehicle loan or lease | Struggling to pay your loan | Lender trying to repossess or disable the vehicle" : "Financial hardship",
"Vehicle loan or lease | Struggling to pay your loan | Loan balance remaining after the vehicle is repossessed and sold" : "Financial hardship",
"Vehicle loan or lease | Struggling to pay your loan | Problem after you declared or threatened to declare bankruptcy" : "Financial hardship",
"Vehicle loan or lease | Unable to get your credit report or credit score | Other problem getting your report or credit score" : "Financial hardship"}













